version: 2
jobs:
  build:
    docker:
    - image: rust:1.30.1
    steps:
    - checkout
    - run:
        name: Embedded Build
        command: |
          cd embedded-rust-proj
          cargo build
    - run:
        name: Setup Rust Fmt
        command: |
          rustup component add rustfmt-preview
    - run:
        name: Setup Clippy
        command: |
          rustup component add rustfmt-preview
    - run:
        name: Build
        command: |
          cargo build
    - run:
        name: Build Release
        command: |
          cargo build --release
    - run:
        name: Strict Build
        command: |
          cargo build --features "strict-build"
    - run:
        name: Strict Release Build
        command: |
          cargo build --release --features "strict-build"
    - run:
        name: Check Rust Fmt
        command: |
          cargo fmt --all -- --check
    - run:
        name: Check Clippy
        command: |
          cargo clippy
    - run:
        name: Run Tests
        command: |
          cargo test


